name: Build, Test and Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Directories
        run: |
          mkdir ./ext /tmp/storedDockerImages
      - name: Download MySQL Connector
        run: |
          curl -o ./ext/mysql-connector-java.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.27/mysql-connector-java-8.0.27.jar
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF##*/} .
      - name: Pack Docker Image
        run: |
          docker save ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF##*/} > /tmp/storedDockerImages/${GITHUB_REF##*/}.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: storedDockerImages
          path: /tmp/storedDockerImages

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: storedDockerImages
          path: /tmp/storedDockerImages
      - name: Load Docker Image
        run: |
          docker load < /tmp/storedDockerImages/${GITHUB_REF##*/}.tar
      - name: Run Test Project
        run: |
          docker run -i --rm \
          -v ${PWD}/test:/opt/soapui/projects \
          -v ${PWD}/test/reports:/opt/soapui/projects/reports \
            ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF##*/} -r -j -J \
              -f /opt/soapui/projects/reports \
              -I /opt/soapui/projects/TestProject-soapui-project.xml

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: storedDockerImages
          path: /tmp/storedDockerImages
      - name: Load Docker Image
        run: |
          docker load < /tmp/storedDockerImages/${GITHUB_REF##*/}.tar
      - name: Add Latest Tag To Docker Image
        run: |
          docker tag ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF##*/} ghcr.io/${GITHUB_REPOSITORY}:latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker Image with Tag ${GITHUB_REF##*/}
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF##*/}
      - name: Push Docker Image with Tag latest
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY}:latest
